use super::register::{Register, RegisterPair, RegisterOp, RegisterPairOp};
use super::condition::{Condition, ConditionOpCode};
use super::{Address, Port};

pub type Word = u8;

#[derive(Debug, PartialEq, Eq, Hash)]
pub enum Instruction {
    MOV(Register, Register),
    MVI(Register, u8),
    LXI(RegisterPair, (u8, u8)),
    LDA(Address),
    STA(Address),
    LHLD(Address),
    SHLD(Address),
    LDAX(RegisterPair),
    STAX(RegisterPair),
    XCHG,
    ADD(Register),
    ADI(u8),
    ADC(Register),
    ACI(u8),
    SUB(Register),
    SUI(u8),
    SBB(Register),
    SBI(u8),
    INR(Register),
    DCR(Register),
    INX(RegisterPair),
    DCX(RegisterPair),
    DAD(RegisterPair),
    DAA,
    ANA(Register),
    ANI(u8),
    ORA(Register),
    ORI(u8),
    XRA(Register),
    XRI(u8),
    CMP(Register),
    CPI(u8),
    RLC,
    RRC,
    RAL,
    RAR,
    RIM,
    RETCOND(Condition),
    RET,
    SIM,
    CMA,
    CMC,
    STC,
    JMP(Address),
    JCOND(Condition, Address),
    CALL(Address),
    CCOND(Condition, Address),
    RST(u8),
    PCHL,
    PUSH(RegisterPair),
    PUSH_PSW,
    POP(RegisterPair),
    POP_PSW,
    XTHL,
    SPHL,
    IN(Port),
    OUT(Port),
    EI,
    DI,
    HLT,
    NOP,
}

impl Instruction {
    pub fn get_size(&self) -> u16 {
        match self {
            Instruction::LXI(_, _) => 3,
            Instruction::MVI(_, _) => 2,
            Instruction::SHLD(_) => 3,
            Instruction::LHLD(_) => 3,
            Instruction::STA(_) => 3,
            Instruction::LDA(_) => 3,
            Instruction::JCOND(_, _) => 3,
            Instruction::JMP(_) => 3,
            Instruction::CCOND(_, _) => 3,
            Instruction::ADI(_) => 2,
            Instruction::CALL(_) => 3,
            Instruction::ACI(_) => 2,
            Instruction::OUT(_) => 2,
            Instruction::IN(_) => 2,
            Instruction::SUI(_) => 2,
            Instruction::SBI(_) => 2,
            Instruction::ANI(_) => 2,
            Instruction::XRI(_) => 2,
            Instruction::ORI(_) => 2,
            Instruction::CPI(_) => 2,
            _ => 1
        }
    }
}